<script src="/aplicacao/agenda-telefonica/public/js/agenda/formCadastrar.js" type="text/javascript"></script>
<script>
    CadastrarContato.init();
</script>
<div class="container-fluid">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="#">Agenda</a>
      </li>
      <li class="breadcrumb-item active">Novo Contato</li>
    </ol>
</div>

<div class="container">
    <form class="form-validation" novalidate>
        <div class="card">
            <div class="card-header">Novo Contato</div>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="font-weight-bold text-muted">Nome Contato</label>
                        <input type="text" class="form-control form-control-sm" name="txtNomeContato" id="nomeRelDownload" required />
                        <div class="invalid-feedback">
                            Campo obrigatório.
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <label class="font-weight-bold text-muted">Celular</label>
                        <input type="text" class="form-control form-control-sm" name="txtTelefone" id="txtTelefone" required />
                        <div class="invalid-feedback">
                            Campo obrigatório.
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <label class="font-weight-bold text-muted">Email</label>
                        <input type="email" class="form-control form-control-sm" name="txtEmail" id="txtEmail" required />
                        <div class="invalid-feedback">
                            Campo obrigatório.
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <label class="font-weight-bold text-muted">Grupo</label>
                        <select class="form-control-sm custom-select" name="slcGrupo" id="slcGrupo" required></select>
                        <div class="invalid-feedback">
                            Campo obrigatório.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-2">
                        <button type="button" id="btnCadastrarContato" class="btn btn-sm btn-dark">Salvar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Sticky Footer -->
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Development - Wagner Lamoglia 021976003581</span>
    </div>
  </div>
</footer>